Removed probe.

diff --git a/.github/workflows/deploy-to.openshift-dev.yml b/.github/workflows/deploy-to.openshift-dev.yml
--- a/.github/workflows/deploy-to.openshift-dev.yml
+++ b/.github/workflows/deploy-to.openshift-dev.yml
@@ -145,26 +145,26 @@ jobs:
       # https://github.com/redhat-actions/oc-login#readme
     - uses: actions/checkout@v2
 
-    - name: Deploy Patroni (If required)
-      run: |
-        set -eux
-        # Login to OpenShift and select project
-        oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
-        oc project ${{ env.OPENSHIFT_NAMESPACE }}
-        
-        patroni=`oc get statefulset ${{ env.APP_NAME }}-pgsql-${{ env.TARGET_ENV }} 2> /dev/null || true && echo "NOT_FOUND"`
-        if [[ "$patroni" == "NOT_FOUND" ]]; then
-          echo "Not Found"
-          # Process and apply secret deployment template
-          oc process -f tools/openshift/patroni-postgresql-secrets.yaml -p NAME=${{ env.APP_NAME }}-pgsql -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p APP_DB_NAME=${{ env.APP_NAME }} -p APP_DB_USERNAME=${{ env.APP_NAME }}  \
-          | oc apply -f -
-          
-          # Process and apply deployment template
-          oc process -f tools/openshift/patroni-postgresql.yaml -p NAME=${{ env.APP_NAME }}-pgsql -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p INSTANCE=${{ env.APP_NAME }}-pgsql \
-          | oc apply -f -
-        else
-          echo "Found"
-        fi
+#    - name: Deploy Patroni (If required)
+#      run: |
+#        set -eux
+#        # Login to OpenShift and select project
+#        oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
+#        oc project ${{ env.OPENSHIFT_NAMESPACE }}
+#
+#        patroni=`oc get statefulset ${{ env.APP_NAME }}-pgsql-${{ env.TARGET_ENV }} 2> /dev/null || true && echo "NOT_FOUND"`
+#        if [[ "$patroni" == "NOT_FOUND" ]]; then
+#          echo "Not Found"
+#          # Process and apply secret deployment template
+#          oc process -f tools/openshift/patroni-postgresql-secrets.yaml -p NAME=${{ env.APP_NAME }}-pgsql -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p APP_DB_NAME=${{ env.APP_NAME }} -p APP_DB_USERNAME=${{ env.APP_NAME }}  \
+#          | oc apply -f -
+#
+#          # Process and apply deployment template
+#          oc process -f tools/openshift/patroni-postgresql.yaml -p NAME=${{ env.APP_NAME }}-pgsql -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p INSTANCE=${{ env.APP_NAME }}-pgsql \
+#          | oc apply -f -
+#        else
+#          echo "Found"
+#        fi
 
     - name: Deploy API
       run: |
@@ -178,11 +178,11 @@ jobs:
         
         oc tag ${{ steps.push-image.outputs.registry-path }} ${{ env.REPO_NAME }}-${{ env.BRANCH }}:${{ env.TAG }}
         
-        echo "::add-mask::$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-pgsql-pgsql-${{ env.TARGET_ENV }} | sed -n 's/.*"app-db-username": "\(.*\)",/\1/p' | base64 --decode)"
-        echo "::add-mask::$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-pgsql-pgsql-${{ env.TARGET_ENV }} | sed -n 's/.*"app-db-password": "\(.*\)",/\1/p' | base64 --decode)"
+        echo "::add-mask::$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-patroni | sed -n 's/.*"username-admin": "\(.*\)",/\1/p' | base64 --decode)"
+        echo "::add-mask::$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-patroni | sed -n 's/.*"password-admin": "\(.*\)",/\1/p' | base64 --decode)"
         
-        SOAM_KC_LOAD_USER_ADMIN=$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-pgsql-pgsql-${{ env.TARGET_ENV }} | sed -n 's/.*"app-db-username": "\(.*\)",/\1/p' | base64 --decode) >> /dev/null 2>&1
-        SOAM_KC_LOAD_USER_PASS=$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-pgsql-pgsql-${{ env.TARGET_ENV }} | sed -n 's/.*"app-db-password": "\(.*\)",/\1/p' | base64 --decode) >> /dev/null 2>&1
+        SOAM_KC_LOAD_USER_ADMIN=$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-patroni | sed -n 's/.*"username-admin": "\(.*\)",/\1/p' | base64 --decode) >> /dev/null 2>&1
+        SOAM_KC_LOAD_USER_PASS=$(oc -n ${{ env.OPENSHIFT_NAMESPACE }} -o json get secret ${{ env.APP_NAME }}-patroni | sed -n 's/.*"password-admin": "\(.*\)",/\1/p' | base64 --decode) >> /dev/null 2>&1
         
         echo "::add-mask::jdbc:postgresql://${{ env.APP_NAME }}-pgsql.${{ env.OPENSHIFT_NAMESPACE }}.svc.cluster.local:5432/${{ env.APP_NAME }}"    
         
