Testing.

diff --git a/.github/workflows/marco-test.yml b/.github/workflows/marco-test.yml
--- a/.github/workflows/marco-test.yml
+++ b/.github/workflows/marco-test.yml
@@ -127,18 +127,19 @@ jobs:
         oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
         oc project ${{ env.OPENSHIFT_NAMESPACE }}
 
-        deploy=`oc get statefulset ${{ env.APP_NAME }}-pgsql-${{ env.TARGET_ENV }} 2> /dev/null || true && echo "No set present"`
+        deploy=`oc get statefulset redis 2> /dev/null || true && echo "No set"`
         echo "Deployment: $deploy" 
-        if [[ "$?" -eq 0 ]]; then
-          #Do nothing
+        if [[ "No set" != $deploy ]]; then
+          echo "Found"   
         else
-          # Process and apply secret deployment template
-          oc process -f tools/openshift/patroni-postgresql-secrets.yaml -p NAME=${{ env.APP_NAME }} -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p APP_DB_NAME=${{ env.APP_NAME }} -p APP_DB_USERNAME=${{ env.APP_NAME }}  \
-          | oc apply -f -
-
-          # Process and apply deployment template
-          oc process -f tools/openshift/patroni-postgresql.yaml -p NAME=${{ env.APP_NAME }} -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p INSTANCE=${{ env.APP_NAME }}-pgsql \
-          | oc apply -f -
+             echo "Not Found"
+#          # Process and apply secret deployment template
+#          oc process -f tools/openshift/patroni-postgresql-secrets.yaml -p NAME=${{ env.APP_NAME }} -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p APP_DB_NAME=${{ env.APP_NAME }} -p APP_DB_USERNAME=${{ env.APP_NAME }}  \
+#          | oc apply -f -
+#
+#          # Process and apply deployment template
+#          oc process -f tools/openshift/patroni-postgresql.yaml -p NAME=${{ env.APP_NAME }} -p SUFFIX=-pgsql-${{ env.TARGET_ENV }} -p INSTANCE=${{ env.APP_NAME }}-pgsql \
+#          | oc apply -f -
         fi
 
 
